---
- hosts: www

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-grub",
         grub_pin_kernel_version: "4.8.0-36-generic"
       }


  tasks:
    - debug: msg="Tasks section"
